
#ifndef CHAT_CHANNEL_H
#define CHAT_CHANNEL_H

enum ChatChannel
{
    CHAT_CHANNEL_Say                = 256,
    CHAT_CHANNEL_Tell               = 257,
    CHAT_CHANNEL_Group              = 258,
    CHAT_CHANNEL_Guild              = 259,
    CHAT_CHANNEL_OOC                = 260,
    CHAT_CHANNEL_Auction            = 261,
    CHAT_CHANNEL_Shout              = 262,
    CHAT_CHANNEL_Emote              = 263,
    CHAT_CHANNEL_CastSpell          = 264,
    CHAT_CHANNEL_YouHitOther        = 265,
    CHAT_CHANNEL_OtherHitsYou       = 266,
    CHAT_CHANNEL_YouMissOther       = 267,
    CHAT_CHANNEL_OtherMissesYou     = 268,
    CHAT_CHANNEL_Broadcast          = 269,
    CHAT_CHANNEL_Skill              = 270,
    CHAT_CHANNEL_Disciplines        = 271,
    CHAT_CHANNEL_Default            = 273,
    CHAT_CHANNEL_MerchantOffer      = 275,
    CHAT_CHANNEL_MerchantExchange   = 276,
    CHAT_CHANNEL_YourDeath          = 277,
    CHAT_CHANNEL_OtherDeath         = 278,
    CHAT_CHANNEL_OtherHitOther      = 279,
    CHAT_CHANNEL_OtherMissOther     = 280,
    CHAT_CHANNEL_Who                = 281,
    CHAT_CHANNEL_Yell               = 282,
    CHAT_CHANNEL_NonMelee           = 283,
    CHAT_CHANNEL_SpellWornOff       = 284,
    CHAT_CHANNEL_MoneySplit         = 285,
    CHAT_CHANNEL_Loot               = 286,
    CHAT_CHANNEL_Random             = 287,
    CHAT_CHANNEL_OtherSpells        = 288,
    CHAT_CHANNEL_SpellFailure       = 289,
    CHAT_CHANNEL_ChatChannel        = 290,
    CHAT_CHANNEL_Chat1              = 291,
    CHAT_CHANNEL_Chat2              = 292,
    CHAT_CHANNEL_Chat3              = 293,
    CHAT_CHANNEL_Chat4              = 294,
    CHAT_CHANNEL_Chat5              = 295,
    CHAT_CHANNEL_Chat6              = 296,
    CHAT_CHANNEL_Chat7              = 297,
    CHAT_CHANNEL_Chat8              = 298,
    CHAT_CHANNEL_Chat9              = 299,
    CHAT_CHANNEL_Chat10             = 300,
    CHAT_CHANNEL_MeleeCrit          = 301,
    CHAT_CHANNEL_SpellCrit          = 302,
    CHAT_CHANNEL_TooFarAway         = 303,
    CHAT_CHANNEL_NPCRampage         = 304,
    CHAT_CHANNEL_NPCFurry           = 305,
    CHAT_CHANNEL_NPCEnrage          = 306,
    CHAT_CHANNEL_EchoSay            = 307,
    CHAT_CHANNEL_EchoTell           = 308,
    CHAT_CHANNEL_EchoGroup          = 309,
    CHAT_CHANNEL_EchoGuild          = 310,
    CHAT_CHANNEL_EchoOOC            = 311,
    CHAT_CHANNEL_EchoAuction        = 312,
    CHAT_CHANNEL_EchoShout          = 313,
    CHAT_CHANNEL_EchoEmote          = 314,
    CHAT_CHANNEL_EchoChat1          = 315,
    CHAT_CHANNEL_EchoChat2          = 316,
    CHAT_CHANNEL_EchoChat3          = 317,
    CHAT_CHANNEL_EchoChat4          = 318,
    CHAT_CHANNEL_EchoChat5          = 319,
    CHAT_CHANNEL_EchoChat6          = 320,
    CHAT_CHANNEL_EchoChat7          = 321,
    CHAT_CHANNEL_EchoChat8          = 322,
    CHAT_CHANNEL_EchoChat9          = 323,
    CHAT_CHANNEL_EchoChat10         = 324,
    CHAT_CHANNEL_UnusedAtThisTime   = 325,
    CHAT_CHANNEL_ItemTags           = 326,
    CHAT_CHANNEL_RaidSay            = 327,
    CHAT_CHANNEL_MyPet              = 328,
    CHAT_CHANNEL_DamageShield       = 329,
};

#endif/*CHAT_CHANNEL_H*/
