
#ifndef ENUM_LOGIN_SERVER_STATUS_H
#define ENUM_LOGIN_SERVER_STATUS_H

enum LoginServerStatus
{
    LOGIN_SERVER_STATUS_Up,
    LOGIN_SERVER_STATUS_Down,
    LOGIN_SERVER_STATUS_Locked,
};

#endif/*ENUM_LOGIN_SERVER_STATUS_H*/
