
#ifndef ITEM_STAT_ID_H
#define ITEM_STAT_ID_H

enum ItemStatId
{
    ITEM_STAT_NONE,
    ITEM_STAT_Lore,
    ITEM_STAT_NoDrop,
    ITEM_STAT_NoRent,
    ITEM_STAT_Magic,
    ITEM_STAT_AC,
    ITEM_STAT_DMG,
    ITEM_STAT_Delay,
    ITEM_STAT_Range,
    ITEM_STAT_STR,
    ITEM_STAT_STA,
    ITEM_STAT_CHA,
    ITEM_STAT_DEX,
    ITEM_STAT_AGI,
    ITEM_STAT_INT,
    ITEM_STAT_WIS,
    ITEM_STAT_SvMagic,
    ITEM_STAT_SvFire,
    ITEM_STAT_SvCold,
    ITEM_STAT_SvPoison,
    ITEM_STAT_SvDisease,
    ITEM_STAT_Hp,
    ITEM_STAT_Mana,
    ITEM_STAT_Weight,
    ITEM_STAT_Size,
    ITEM_STAT_Slot,
    ITEM_STAT_Race,
    ITEM_STAT_Class,
    ITEM_STAT_BagSlots,
    ITEM_STAT_BagWeightReduction,
    ITEM_STAT_BagMaxSize,
    ITEM_STAT_SkillModSkillId,
    ITEM_STAT_SkillModValue,
    ITEM_STAT_Texture,
    ITEM_STAT_Tint,
    ITEM_STAT_SpellId,
    ITEM_STAT_SpellEffectType,
    ITEM_STAT_SpellMinLevel,
    ITEM_STAT_CastingTime,
    ITEM_STAT_HasteMinLevel,
    ITEM_STAT_Charges,
    ITEM_STAT_ProcRate,
    ITEM_STAT_Haste,
    ITEM_STAT_Icon,
    ITEM_STAT_VendorBuyPrice,
    ITEM_STAT_VendorSellPrice,
    ITEM_STAT_Model,
    ITEM_STAT_ItemType,
    ITEM_STAT_Light,
};

#endif/*ITEM_STAT_ID_H*/
